/**
 * Test fixtures based on real TDLib data collected via `tg eval`.
 *
 * The `_` discriminator tags are added back (TDLib-over-HTTP strips them).
 * Sensitive data (phone numbers, file paths) is scrubbed.
 * Partial objects are cast via `as Td.*` to satisfy TypeScript.
 */
import type * as Td from 'tdlib-types';

// ---------------------------------------------------------------------------
// Users
// ---------------------------------------------------------------------------

export const USER_ME: Td.user = {
  _: 'user',
  id: 91754006,
  first_name: 'Andrey',
  last_name: '',
  usernames: {
    _: 'usernames',
    active_usernames: ['avemeva'],
    disabled_usernames: [],
    editable_username: 'avemeva',
    collectible_usernames: [],
  },
  phone_number: '',
  status: { _: 'userStatusOffline', was_online: 1772464607 },
  is_premium: true,
  type: { _: 'userTypeRegular' },
} as unknown as Td.user;

export const USER_HY_RID: Td.user = {
  _: 'user',
  id: 6098406782,
  first_name: 'Hy',
  last_name: 'Rid',
  phone_number: '',
  status: { _: 'userStatusOffline', was_online: 1772424135 },
  is_premium: false,
  type: { _: 'userTypeRegular' },
} as unknown as Td.user;

export const USER_MARUSIA: Td.user = {
  _: 'user',
  id: 346928206,
  first_name: 'Маруся',
  last_name: '',
  usernames: {
    _: 'usernames',
    active_usernames: ['naluneteplo'],
    disabled_usernames: [],
    editable_username: 'naluneteplo',
    collectible_usernames: [],
  },
  phone_number: '',
  status: { _: 'userStatusOffline', was_online: 1772463181 },
  is_premium: true,
  emoji_status: {
    _: 'emojiStatus',
    type: { _: 'emojiStatusTypeCustomEmoji', custom_emoji_id: '5316659463606796443' },
    expiration_date: 0,
  },
  type: { _: 'userTypeRegular' },
} as unknown as Td.user;

export const USER_VALIDOL: Td.user = {
  _: 'user',
  id: 112588642,
  first_name: 'Валидол',
  last_name: '',
  usernames: {
    _: 'usernames',
    active_usernames: ['kxt9_8'],
    disabled_usernames: [],
    editable_username: 'kxt9_8',
    collectible_usernames: [],
  },
  phone_number: '',
  status: { _: 'userStatusRecently', by_my_privacy_settings: false },
  is_premium: true,
  emoji_status: {
    _: 'emojiStatus',
    type: { _: 'emojiStatusTypeCustomEmoji', custom_emoji_id: '5393542049674831462' },
    expiration_date: 0,
  },
  type: { _: 'userTypeRegular' },
} as unknown as Td.user;

export const FIXTURE_USERS: Td.user[] = [USER_ME, USER_HY_RID, USER_MARUSIA, USER_VALIDOL];

export const USERS_MAP = new Map<number, Td.user>(FIXTURE_USERS.map((u) => [u.id, u]));

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function ft(text: string, entities: Td.textEntity[] = []): Td.formattedText {
  return { _: 'formattedText', text, entities };
}

function file(id: number, size: number): Td.file {
  return {
    _: 'file',
    id,
    size,
    expected_size: size,
    local: {
      _: 'localFile',
      path: '',
      can_be_downloaded: true,
      can_be_deleted: false,
      is_downloading_active: false,
      is_downloading_completed: false,
      download_offset: 0,
      downloaded_prefix_size: 0,
      downloaded_size: 0,
    },
    remote: {
      _: 'remoteFile',
      id: '',
      unique_id: '',
      is_uploading_active: false,
      is_uploading_completed: true,
      uploaded_size: size,
    },
  } as Td.file;
}

function photoSizes(
  sizes: { type: string; id: number; size: number; width: number; height: number }[],
): Td.photoSize[] {
  return sizes.map((s) => ({
    _: 'photoSize',
    type: s.type,
    photo: file(s.id, s.size),
    width: s.width,
    height: s.height,
    progressive_sizes: [],
  })) as Td.photoSize[];
}

// ---------------------------------------------------------------------------
// Messages
// ---------------------------------------------------------------------------

// text_incoming
export const MSG_TEXT_INCOMING: Td.message = {
  _: 'message',
  id: 751105474560,
  sender_id: { _: 'messageSenderUser', user_id: 6098406782 },
  chat_id: 6098406782,
  is_outgoing: false,
  is_pinned: false,
  is_from_offline: false,
  can_be_saved: true,
  has_timestamped_media: true,
  is_channel_post: false,
  is_paid_star_suggested_post: false,
  is_paid_ton_suggested_post: false,
  contains_unread_mention: false,
  date: 1770743729,
  edit_date: 0,
  unread_reactions: [],
  self_destruct_in: 0,
  auto_delete_in: 0,
  via_bot_user_id: 0,
  sender_business_bot_user_id: 0,
  sender_boost_count: 0,
  paid_message_star_count: 0,
  author_signature: '',
  media_album_id: '0',
  effect_id: '0',
  summary_language_code: '',
  content: {
    _: 'messageText',
    text: ft('All good, take your time.'),
  },
} as unknown as Td.message;

// text_outgoing
export const MSG_TEXT_OUTGOING: Td.message = {
  _: 'message',
  id: 751103377408,
  sender_id: { _: 'messageSenderUser', user_id: 91754006 },
  chat_id: 6098406782,
  is_outgoing: true,
  is_pinned: false,
  is_from_offline: false,
  can_be_saved: true,
  has_timestamped_media: true,
  is_channel_post: false,
  is_paid_star_suggested_post: false,
  is_paid_ton_suggested_post: false,
  contains_unread_mention: false,
  date: 1770740356,
  edit_date: 1770740357,
  unread_reactions: [],
  self_destruct_in: 0,
  auto_delete_in: 0,
  via_bot_user_id: 0,
  sender_business_bot_user_id: 0,
  sender_boost_count: 0,
  paid_message_star_count: 0,
  author_signature: '',
  media_album_id: '0',
  effect_id: '0',
  summary_language_code: '',
  content: {
    _: 'messageText',
    text: ft('Hey, sure, but I am a bit busy atm, will try to get back to it as fast as I can'),
  },
} as unknown as Td.message;

// text_with_entities (also used as with_reactions — same message)
export const MSG_TEXT_WITH_ENTITIES: Td.message = {
  _: 'message',
  id: 750945042432,
  sender_id: { _: 'messageSenderUser', user_id: 6098406782 },
  chat_id: 6098406782,
  is_outgoing: false,
  is_pinned: false,
  is_from_offline: false,
  can_be_saved: true,
  has_timestamped_media: true,
  is_channel_post: false,
  is_paid_star_suggested_post: false,
  is_paid_ton_suggested_post: false,
  contains_unread_mention: false,
  date: 1770704228,
  edit_date: 0,
  interaction_info: {
    _: 'messageInteractionInfo',
    view_count: 0,
    forward_count: 0,
    reactions: {
      _: 'messageReactions',
      reactions: [
        {
          _: 'messageReaction',
          type: { _: 'reactionTypeEmoji', emoji: '👍' },
          total_count: 1,
          is_chosen: true,
          used_sender_id: { _: 'messageSenderUser', user_id: 91754006 },
          recent_sender_ids: [{ _: 'messageSenderUser', user_id: 91754006 }],
        },
      ],
      are_tags: false,
      paid_reactors: [],
      can_get_added_reactions: false,
    },
  },
  unread_reactions: [],
  self_destruct_in: 0,
  auto_delete_in: 0,
  via_bot_user_id: 0,
  sender_business_bot_user_id: 0,
  sender_boost_count: 0,
  paid_message_star_count: 0,
  author_signature: '',
  media_album_id: '0',
  effect_id: '0',
  summary_language_code: '',
  content: {
    _: 'messageText',
    text: ft(
      'Hey Andery! Hope you had a great week \u{1F60A}\nBased on your last feedback, my research engine has made some big progress. I\u2019ll send you a short demo video next \u2014 would love for you to take a look and see if it\u2019s working the way you had in mind.\nI\u2019ll keep iterating on a few more versions, and I\u2019m aiming to have it live by the end of this month.\nAlso, I just bought a domain: rabbitrsearch.com, lol \u{1F407}\nFollowing the problemhunt.pro principle, you\u2019ll get 1% equity in this product. After the app officially launches, I\u2019ll sync with you on how to properly handle this once there\u2019s revenue coming in.\nHope you have a smooth and productive week ahead!',
      [
        { _: 'textEntity', offset: 103, length: 12, type: { _: 'textEntityTypeBold' } },
        { _: 'textEntity', offset: 371, length: 17, type: { _: 'textEntityTypeUrl' } },
        { _: 'textEntity', offset: 371, length: 17, type: { _: 'textEntityTypeUrl' } },
        { _: 'textEntity', offset: 411, length: 15, type: { _: 'textEntityTypeUrl' } },
        { _: 'textEntity', offset: 411, length: 15, type: { _: 'textEntityTypeUrl' } },
        { _: 'textEntity', offset: 449, length: 9, type: { _: 'textEntityTypeBold' } },
      ],
    ),
  },
} as unknown as Td.message;

// text_with_link_preview
export const MSG_TEXT_WITH_LINK_PREVIEW: Td.message = {
  _: 'message',
  id: 748996788224,
  sender_id: { _: 'messageSenderUser', user_id: 91754006 },
  chat_id: 6098406782,
  is_outgoing: true,
  is_pinned: false,
  is_from_offline: false,
  can_be_saved: true,
  has_timestamped_media: true,
  is_channel_post: false,
  is_paid_star_suggested_post: false,
  is_paid_ton_suggested_post: false,
  contains_unread_mention: false,
  date: 1769944567,
  edit_date: 0,
  unread_reactions: [],
  self_destruct_in: 0,
  auto_delete_in: 0,
  via_bot_user_id: 0,
  sender_business_bot_user_id: 0,
  sender_boost_count: 0,
  paid_message_star_count: 0,
  author_signature: '',
  media_album_id: '0',
  effect_id: '0',
  summary_language_code: '',
  content: {
    _: 'messageText',
    text: ft('Here is the place where you can find mentors:\nhttps://t.me/startupseurope', [
      { _: 'textEntity', offset: 46, length: 27, type: { _: 'textEntityTypeUrl' } },
    ]),
    link_preview: {
      _: 'linkPreview',
      url: 'https://t.me/startupseurope',
      display_url: 't.me/startupseurope',
      site_name: 'Telegram',
      title: 'Алекс Беляев @ Community Sprints',
      description: ft(
        'Co-founder @ Community Sprints: сommunity-driven platform to grow career & business skills\n\nПишу о развитии компании в Европе и делюсь полезными материалами  про карьеру и бизнес\n\nStartupWiseGuys.com alumni \n\nDM @belalex',
        [
          {
            _: 'textEntity',
            offset: 180,
            length: 19,
            type: { _: 'textEntityTypeUrl' },
          },
          {
            _: 'textEntity',
            offset: 212,
            length: 8,
            type: { _: 'textEntityTypeMention' },
          },
        ],
      ),
      author: '',
      type: {
        _: 'linkPreviewTypePhoto',
        photo: {
          _: 'photo',
          has_stickers: false,
          sizes: photoSizes([
            { type: 'a', id: 3464, size: 8402, width: 160, height: 160 },
            { type: 'b', id: 3465, size: 24675, width: 320, height: 320 },
            { type: 'c', id: 3466, size: 86394, width: 640, height: 640 },
          ]),
        },
      },
      has_large_media: false,
      show_large_media: false,
      show_media_above_description: false,
      skip_confirmation: true,
      show_above_text: false,
      instant_view_version: 0,
    },
  },
} as unknown as Td.message;

// photo_album (first photo in the album)
export const MSG_PHOTO_ALBUM: Td.message = {
  _: 'message',
  id: 755108937728,
  sender_id: { _: 'messageSenderUser', user_id: 346928206 },
  chat_id: 346928206,
  is_outgoing: false,
  is_pinned: false,
  is_from_offline: false,
  can_be_saved: true,
  has_timestamped_media: true,
  is_channel_post: false,
  is_paid_star_suggested_post: false,
  is_paid_ton_suggested_post: false,
  contains_unread_mention: false,
  date: 1772462041,
  edit_date: 0,
  forward_info: {
    _: 'messageForwardInfo',
    origin: { _: 'messageOriginUser', sender_user_id: 346928206 },
    date: 1772461985,
    public_service_announcement_type: '',
  },
  unread_reactions: [],
  self_destruct_in: 0,
  auto_delete_in: 0,
  via_bot_user_id: 0,
  sender_business_bot_user_id: 0,
  sender_boost_count: 0,
  paid_message_star_count: 0,
  author_signature: '',
  media_album_id: '14179696327798362',
  effect_id: '0',
  summary_language_code: '',
  content: {
    _: 'messagePhoto',
    photo: {
      _: 'photo',
      has_stickers: false,
      sizes: photoSizes([
        { type: 'm', id: 18143, size: 19390, width: 240, height: 320 },
        { type: 'x', id: 18144, size: 83814, width: 600, height: 800 },
        { type: 'y', id: 18145, size: 115043, width: 960, height: 1280 },
      ]),
    },
    caption: ft(''),
    show_caption_above_media: false,
    has_spoiler: false,
    is_secret: false,
  },
} as unknown as Td.message;

// photo_album_1 (second photo in the same album)
export const MSG_PHOTO_ALBUM_1: Td.message = {
  _: 'message',
  id: 755107889152,
  sender_id: { _: 'messageSenderUser', user_id: 346928206 },
  chat_id: 346928206,
  is_outgoing: false,
  is_pinned: false,
  is_from_offline: false,
  can_be_saved: true,
  has_timestamped_media: true,
  is_channel_post: false,
  is_paid_star_suggested_post: false,
  is_paid_ton_suggested_post: false,
  contains_unread_mention: false,
  date: 1772462040,
  edit_date: 0,
  forward_info: {
    _: 'messageForwardInfo',
    origin: { _: 'messageOriginUser', sender_user_id: 346928206 },
    date: 1772461985,
    public_service_announcement_type: '',
  },
  unread_reactions: [],
  self_destruct_in: 0,
  auto_delete_in: 0,
  via_bot_user_id: 0,
  sender_business_bot_user_id: 0,
  sender_boost_count: 0,
  paid_message_star_count: 0,
  author_signature: '',
  media_album_id: '14179696327798362',
  effect_id: '0',
  summary_language_code: '',
  content: {
    _: 'messagePhoto',
    photo: {
      _: 'photo',
      has_stickers: false,
      sizes: photoSizes([
        { type: 'm', id: 18140, size: 21761, width: 320, height: 240 },
        { type: 'x', id: 18141, size: 110005, width: 800, height: 600 },
        { type: 'y', id: 18142, size: 161727, width: 1280, height: 960 },
      ]),
    },
    caption: ft(''),
    show_caption_above_media: false,
    has_spoiler: false,
    is_secret: false,
  },
} as unknown as Td.message;

// photo_single (from a supergroup)
export const MSG_PHOTO_SINGLE: Td.message = {
  _: 'message',
  id: 103629717504,
  sender_id: { _: 'messageSenderUser', user_id: 1042690371 },
  chat_id: -1001731417779,
  is_outgoing: false,
  is_pinned: false,
  is_from_offline: false,
  can_be_saved: true,
  has_timestamped_media: true,
  is_channel_post: false,
  is_paid_star_suggested_post: false,
  is_paid_ton_suggested_post: false,
  contains_unread_mention: false,
  date: 1772461171,
  edit_date: 0,
  interaction_info: {
    _: 'messageInteractionInfo',
    view_count: 0,
    forward_count: 0,
    reply_info: {
      _: 'messageReplyInfo',
      reply_count: 0,
      recent_replier_ids: [],
      last_read_inbox_message_id: 0,
      last_read_outbox_message_id: 0,
      last_message_id: 0,
    },
  },
  unread_reactions: [],
  self_destruct_in: 0,
  auto_delete_in: 0,
  via_bot_user_id: 0,
  sender_business_bot_user_id: 0,
  sender_boost_count: 0,
  paid_message_star_count: 0,
  author_signature: '',
  media_album_id: '0',
  effect_id: '0',
  summary_language_code: '',
  content: {
    _: 'messagePhoto',
    photo: {
      _: 'photo',
      has_stickers: false,
      sizes: photoSizes([
        { type: 'm', id: 18006, size: 13058, width: 320, height: 180 },
        { type: 'x', id: 18007, size: 51767, width: 800, height: 450 },
        { type: 'y', id: 18008, size: 109591, width: 1280, height: 720 },
      ]),
    },
    caption: ft('а ещё в футбольных менеджерах вот такая хуйня бывает если долго играть'),
    show_caption_above_media: false,
    has_spoiler: false,
    is_secret: false,
  },
} as unknown as Td.message;

// video
export const MSG_VIDEO: Td.message = {
  _: 'message',
  id: 750947139584,
  sender_id: { _: 'messageSenderUser', user_id: 6098406782 },
  chat_id: 6098406782,
  is_outgoing: false,
  is_pinned: false,
  is_from_offline: false,
  can_be_saved: true,
  has_timestamped_media: true,
  is_channel_post: false,
  is_paid_star_suggested_post: false,
  is_paid_ton_suggested_post: false,
  contains_unread_mention: false,
  date: 1770713733,
  edit_date: 0,
  unread_reactions: [],
  self_destruct_in: 0,
  auto_delete_in: 0,
  via_bot_user_id: 0,
  sender_business_bot_user_id: 0,
  sender_boost_count: 0,
  paid_message_star_count: 0,
  author_signature: '',
  media_album_id: '14165709864191253',
  effect_id: '0',
  summary_language_code: '',
  content: {
    _: 'messageVideo',
    video: {
      _: 'video',
      duration: 637,
      width: 848,
      height: 512,
      file_name: 'IMG_6172.MP4',
      mime_type: 'video/mp4',
      has_stickers: false,
      supports_streaming: true,
      video: file(9594, 26753400),
      alternative_videos: [],
      storyboards: [],
    },
    alternative_videos: [],
    storyboards: [],
    start_timestamp: 0,
    caption: ft(''),
    show_caption_above_media: false,
    has_spoiler: false,
    is_secret: false,
  },
} as unknown as Td.message;

// voice_incoming
export const MSG_VOICE_INCOMING: Td.message = {
  _: 'message',
  id: 754512297984,
  sender_id: { _: 'messageSenderUser', user_id: 346928206 },
  chat_id: 346928206,
  is_outgoing: false,
  is_pinned: false,
  is_from_offline: false,
  can_be_saved: true,
  has_timestamped_media: true,
  is_channel_post: false,
  is_paid_star_suggested_post: false,
  is_paid_ton_suggested_post: false,
  contains_unread_mention: false,
  date: 1772367341,
  edit_date: 0,
  unread_reactions: [],
  self_destruct_in: 0,
  auto_delete_in: 0,
  via_bot_user_id: 0,
  sender_business_bot_user_id: 0,
  sender_boost_count: 0,
  paid_message_star_count: 0,
  author_signature: '',
  media_album_id: '0',
  effect_id: '0',
  summary_language_code: '',
  content: {
    _: 'messageVoiceNote',
    voice_note: {
      _: 'voiceNote',
      duration: 4,
      waveform:
        'AAAAAAAAAAAAAAAAAMABAgAAABEAgKJcMyeJc5QRY4BhkCEiqGTIGAEAAIAQopyB0CgigEEEIYWEAAAAAIAB',
      mime_type: 'audio/ogg',
      voice: file(17685, 19067),
    },
    caption: ft(''),
    is_listened: true,
  },
} as unknown as Td.message;

// voice_outgoing
export const MSG_VOICE_OUTGOING: Td.message = {
  _: 'message',
  id: 754124324864,
  sender_id: { _: 'messageSenderUser', user_id: 91754006 },
  chat_id: 346928206,
  is_outgoing: true,
  is_pinned: false,
  is_from_offline: false,
  can_be_saved: true,
  has_timestamped_media: true,
  is_channel_post: false,
  is_paid_star_suggested_post: false,
  is_paid_ton_suggested_post: false,
  contains_unread_mention: false,
  date: 1772124756,
  edit_date: 0,
  unread_reactions: [],
  self_destruct_in: 0,
  auto_delete_in: 0,
  via_bot_user_id: 0,
  sender_business_bot_user_id: 0,
  sender_boost_count: 0,
  paid_message_star_count: 0,
  author_signature: '',
  media_album_id: '0',
  effect_id: '0',
  summary_language_code: '',
  content: {
    _: 'messageVoiceNote',
    voice_note: {
      _: 'voiceNote',
      duration: 2,
      waveform:
        'AAAAAAAAAAAAAAAAAAC49H9P3+We3////9/Tp/KV/L6n/v9fvlNKEepmKhm9UtL/s2TUf8//l/kyIQAAAAAA',
      mime_type: 'audio/ogg',
      voice: file(17705, 9419),
    },
    caption: ft(''),
    is_listened: false,
  },
} as unknown as Td.message;

// video_note
export const MSG_VIDEO_NOTE: Td.message = {
  _: 'message',
  id: 754513346560,
  sender_id: { _: 'messageSenderUser', user_id: 346928206 },
  chat_id: 346928206,
  is_outgoing: false,
  is_pinned: false,
  is_from_offline: false,
  can_be_saved: true,
  has_timestamped_media: true,
  is_channel_post: false,
  is_paid_star_suggested_post: false,
  is_paid_ton_suggested_post: false,
  contains_unread_mention: false,
  date: 1772367487,
  edit_date: 0,
  unread_reactions: [],
  self_destruct_in: 0,
  auto_delete_in: 0,
  via_bot_user_id: 0,
  sender_business_bot_user_id: 0,
  sender_boost_count: 0,
  paid_message_star_count: 0,
  author_signature: '',
  media_album_id: '0',
  effect_id: '0',
  summary_language_code: '',
  content: {
    _: 'messageVideoNote',
    video_note: {
      _: 'videoNote',
      duration: 4,
      waveform:
        'QAwCAIAwCAGAgBgMAgBgGAgCgIAgCAIAgCgaL4ZF+j5vl6OIoD8NR/i6T5Pn+X5Pl+Jpvl+T5fm+X5fn+L4=',
      length: 300,
      video: file(17684, 324806),
    },
    is_viewed: false,
    is_secret: false,
  },
} as unknown as Td.message;

// sticker_incoming
export const MSG_STICKER_INCOMING: Td.message = {
  _: 'message',
  id: 754425266176,
  sender_id: { _: 'messageSenderUser', user_id: 346928206 },
  chat_id: 346928206,
  is_outgoing: false,
  is_pinned: false,
  is_from_offline: false,
  can_be_saved: true,
  has_timestamped_media: true,
  is_channel_post: false,
  is_paid_star_suggested_post: false,
  is_paid_ton_suggested_post: false,
  contains_unread_mention: false,
  date: 1772284812,
  edit_date: 0,
  unread_reactions: [],
  self_destruct_in: 0,
  auto_delete_in: 0,
  via_bot_user_id: 0,
  sender_business_bot_user_id: 0,
  sender_boost_count: 0,
  paid_message_star_count: 0,
  author_signature: '',
  media_album_id: '0',
  effect_id: '0',
  summary_language_code: '',
  content: {
    _: 'messageSticker',
    sticker: {
      _: 'sticker',
      id: '6224473141750535648',
      set_id: '7570335112848474743',
      width: 512,
      height: 512,
      emoji: '⭐',
      sticker: file(17689, 12094),
      format: { _: 'stickerFormatWebp' },
      full_type: { _: 'stickerFullTypeRegular' },
      outline: [],
      type: { _: 'stickerTypeRegular' },
    },
    is_premium: false,
  },
} as unknown as Td.message;

// animation (GIF)
export const MSG_ANIMATION: Td.message = {
  _: 'message',
  id: 754400100352,
  sender_id: { _: 'messageSenderUser', user_id: 346928206 },
  chat_id: 346928206,
  is_outgoing: false,
  is_pinned: false,
  is_from_offline: false,
  can_be_saved: true,
  has_timestamped_media: true,
  is_channel_post: false,
  is_paid_star_suggested_post: false,
  is_paid_ton_suggested_post: false,
  contains_unread_mention: false,
  date: 1772282433,
  edit_date: 0,
  unread_reactions: [],
  self_destruct_in: 0,
  auto_delete_in: 0,
  via_bot_user_id: 0,
  sender_business_bot_user_id: 0,
  sender_boost_count: 0,
  paid_message_star_count: 0,
  author_signature: '',
  media_album_id: '0',
  effect_id: '0',
  summary_language_code: '',
  content: {
    _: 'messageAnimation',
    animation: {
      _: 'animation',
      duration: 2,
      width: 288,
      height: 230,
      file_name: 'noice-nice.mp4',
      mime_type: 'video/mp4',
      has_stickers: false,
      animation: file(17702, 75436),
    },
    caption: ft(''),
    show_caption_above_media: false,
    has_spoiler: false,
    is_secret: false,
  },
} as unknown as Td.message;

// forwarded text message
export const MSG_FORWARDED: Td.message = {
  _: 'message',
  id: 755109986304,
  sender_id: { _: 'messageSenderUser', user_id: 346928206 },
  chat_id: 346928206,
  is_outgoing: false,
  is_pinned: false,
  is_from_offline: false,
  can_be_saved: true,
  has_timestamped_media: true,
  is_channel_post: false,
  is_paid_star_suggested_post: false,
  is_paid_ton_suggested_post: false,
  contains_unread_mention: false,
  date: 1772462041,
  edit_date: 0,
  forward_info: {
    _: 'messageForwardInfo',
    origin: { _: 'messageOriginUser', sender_user_id: 346928206 },
    date: 1772461989,
    public_service_announcement_type: '',
  },
  unread_reactions: [],
  self_destruct_in: 0,
  auto_delete_in: 0,
  via_bot_user_id: 0,
  sender_business_bot_user_id: 0,
  sender_boost_count: 0,
  paid_message_star_count: 0,
  author_signature: '',
  media_album_id: '0',
  effect_id: '0',
  summary_language_code: '',
  content: {
    _: 'messageText',
    text: ft('прошла неделя, а цвет уже изменился\nтак круто'),
  },
} as unknown as Td.message;

// reply message
export const MSG_REPLY: Td.message = {
  _: 'message',
  id: 749007273984,
  sender_id: { _: 'messageSenderUser', user_id: 91754006 },
  chat_id: 6098406782,
  is_outgoing: true,
  is_pinned: false,
  is_from_offline: false,
  can_be_saved: true,
  has_timestamped_media: false,
  is_channel_post: false,
  is_paid_star_suggested_post: false,
  is_paid_ton_suggested_post: false,
  contains_unread_mention: false,
  date: 1769945234,
  edit_date: 0,
  unread_reactions: [],
  reply_to: {
    _: 'messageReplyToMessage',
    chat_id: 6098406782,
    message_id: 748995739648,
    checklist_task_id: 0,
    origin_send_date: 0,
  },
  self_destruct_in: 0,
  auto_delete_in: 0,
  via_bot_user_id: 0,
  sender_business_bot_user_id: 0,
  sender_boost_count: 0,
  paid_message_star_count: 0,
  author_signature: '',
  media_album_id: '0',
  effect_id: '0',
  summary_language_code: '',
  content: {
    _: 'messageText',
    text: ft('^'),
  },
} as unknown as Td.message;

// Alias: with_reactions is the same message as text_with_entities
export const MSG_WITH_REACTIONS = MSG_TEXT_WITH_ENTITIES;

export const FIXTURE_MESSAGES: Td.message[] = [
  MSG_TEXT_INCOMING,
  MSG_TEXT_OUTGOING,
  MSG_TEXT_WITH_ENTITIES,
  MSG_TEXT_WITH_LINK_PREVIEW,
  MSG_PHOTO_ALBUM,
  MSG_PHOTO_ALBUM_1,
  MSG_PHOTO_SINGLE,
  MSG_VIDEO,
  MSG_VOICE_INCOMING,
  MSG_VOICE_OUTGOING,
  MSG_VIDEO_NOTE,
  MSG_STICKER_INCOMING,
  MSG_ANIMATION,
  MSG_FORWARDED,
  MSG_REPLY,
];

// ---------------------------------------------------------------------------
// Chats
// ---------------------------------------------------------------------------

export const CHAT_HY_RID: Td.chat = {
  _: 'chat',
  id: 6098406782,
  title: 'Hy Rid',
  type: { _: 'chatTypePrivate', user_id: 6098406782 },
  permissions: {
    _: 'chatPermissions',
    can_send_basic_messages: true,
    can_send_audios: true,
    can_send_documents: true,
    can_send_photos: true,
    can_send_videos: true,
    can_send_video_notes: true,
    can_send_voice_notes: true,
    can_send_polls: true,
    can_send_other_messages: true,
    can_add_link_previews: true,
    can_change_info: false,
    can_invite_users: false,
    can_pin_messages: true,
    can_create_topics: false,
  },
  last_message: MSG_TEXT_INCOMING,
  positions: [
    {
      _: 'chatPosition',
      list: { _: 'chatListMain' },
      order: '9221294784512000002',
      is_pinned: true,
    },
  ],
  has_protected_content: false,
  is_translatable: true,
  is_marked_as_unread: false,
  is_blocked: false,
  has_scheduled_messages: false,
  can_be_deleted_only_for_self: true,
  can_be_deleted_for_all_users: true,
  can_be_reported: false,
  default_disable_notification: false,
  unread_count: 0,
  last_read_inbox_message_id: 751105474560,
  last_read_outbox_message_id: 751103377408,
  unread_mention_count: 0,
  unread_reaction_count: 0,
  notification_settings: {
    _: 'chatNotificationSettings',
    use_default_mute_for: true,
    mute_for: 0,
    use_default_sound: true,
    sound_id: '-1',
    use_default_show_preview: true,
    show_preview: false,
    use_default_mute_stories: true,
    mute_stories: false,
    use_default_story_sound: true,
    story_sound_id: '-1',
    use_default_show_story_poster: true,
    show_story_poster: true,
    use_default_disable_pinned_message_notifications: true,
    disable_pinned_message_notifications: false,
    use_default_disable_mention_notifications: true,
    disable_mention_notifications: false,
  },
  available_reactions: {
    _: 'chatAvailableReactionsAll',
    max_reaction_count: 11,
  },
  message_auto_delete_time: 0,
  theme_name: '',
  video_chat: { _: 'videoChat', group_call_id: 0, has_participants: false },
  reply_markup_message_id: 0,
  client_data: '',
} as unknown as Td.chat;

export const CHAT_MARUSIA: Td.chat = {
  _: 'chat',
  id: 346928206,
  title: 'Маруся',
  type: { _: 'chatTypePrivate', user_id: 346928206 },
  permissions: {
    _: 'chatPermissions',
    can_send_basic_messages: true,
    can_send_audios: true,
    can_send_documents: true,
    can_send_photos: true,
    can_send_videos: true,
    can_send_video_notes: true,
    can_send_voice_notes: true,
    can_send_polls: true,
    can_send_other_messages: true,
    can_add_link_previews: true,
    can_change_info: false,
    can_invite_users: false,
    can_pin_messages: true,
    can_create_topics: false,
  },
  last_message: MSG_FORWARDED,
  positions: [
    {
      _: 'chatPosition',
      list: { _: 'chatListMain' },
      order: '9221294784512000001',
      is_pinned: true,
    },
  ],
  has_protected_content: false,
  is_translatable: false,
  is_marked_as_unread: false,
  is_blocked: false,
  has_scheduled_messages: false,
  can_be_deleted_only_for_self: true,
  can_be_deleted_for_all_users: true,
  can_be_reported: false,
  default_disable_notification: false,
  unread_count: 0,
  last_read_inbox_message_id: 755109986304,
  last_read_outbox_message_id: 754423169024,
  unread_mention_count: 0,
  unread_reaction_count: 0,
  notification_settings: {
    _: 'chatNotificationSettings',
    use_default_mute_for: false,
    mute_for: 0,
    use_default_sound: true,
    sound_id: '-1',
    use_default_show_preview: true,
    show_preview: false,
    use_default_mute_stories: true,
    mute_stories: false,
    use_default_story_sound: true,
    story_sound_id: '-1',
    use_default_show_story_poster: true,
    show_story_poster: true,
    use_default_disable_pinned_message_notifications: true,
    disable_pinned_message_notifications: false,
    use_default_disable_mention_notifications: true,
    disable_mention_notifications: false,
  },
  available_reactions: {
    _: 'chatAvailableReactionsAll',
    max_reaction_count: 11,
  },
  message_auto_delete_time: 0,
  theme_name: '',
  video_chat: { _: 'videoChat', group_call_id: 0, has_participants: false },
  reply_markup_message_id: 0,
  client_data: '',
} as unknown as Td.chat;

export const CHAT_SUPERGROUP: Td.chat = {
  _: 'chat',
  id: -1001731417779,
  title: 'Башня маркарянов',
  type: { _: 'chatTypeSupergroup', supergroup_id: 1731417779, is_channel: false },
  permissions: {
    _: 'chatPermissions',
    can_send_basic_messages: true,
    can_send_audios: true,
    can_send_documents: true,
    can_send_photos: true,
    can_send_videos: true,
    can_send_video_notes: true,
    can_send_voice_notes: true,
    can_send_polls: true,
    can_send_other_messages: true,
    can_add_link_previews: true,
    can_change_info: true,
    can_invite_users: true,
    can_pin_messages: true,
    can_create_topics: true,
  },
  positions: [
    {
      _: 'chatPosition',
      list: { _: 'chatListMain' },
      order: '7612670652729885202',
      is_pinned: false,
    },
  ],
  has_protected_content: false,
  is_translatable: false,
  is_marked_as_unread: false,
  is_blocked: false,
  has_scheduled_messages: false,
  can_be_deleted_only_for_self: true,
  can_be_deleted_for_all_users: false,
  can_be_reported: true,
  default_disable_notification: false,
  unread_count: 0,
  last_read_inbox_message_id: 103634960384,
  last_read_outbox_message_id: 103632863232,
  unread_mention_count: 0,
  unread_reaction_count: 0,
  notification_settings: {
    _: 'chatNotificationSettings',
    use_default_mute_for: false,
    mute_for: 375018407,
    use_default_sound: false,
    sound_id: '0',
    use_default_show_preview: true,
    show_preview: false,
    use_default_mute_stories: true,
    mute_stories: false,
    use_default_story_sound: true,
    story_sound_id: '-1',
    use_default_show_story_poster: true,
    show_story_poster: true,
    use_default_disable_pinned_message_notifications: true,
    disable_pinned_message_notifications: false,
    use_default_disable_mention_notifications: true,
    disable_mention_notifications: false,
  },
  available_reactions: {
    _: 'chatAvailableReactionsAll',
    max_reaction_count: 11,
  },
  message_auto_delete_time: 0,
  theme_name: '',
  video_chat: { _: 'videoChat', group_call_id: 0, has_participants: false },
  reply_markup_message_id: 0,
  client_data: '',
} as unknown as Td.chat;

export const CHAT_VALIDOL: Td.chat = {
  _: 'chat',
  id: 112588642,
  title: 'Валидол',
  type: { _: 'chatTypePrivate', user_id: 112588642 },
  permissions: {
    _: 'chatPermissions',
    can_send_basic_messages: true,
    can_send_audios: true,
    can_send_documents: true,
    can_send_photos: true,
    can_send_videos: true,
    can_send_video_notes: true,
    can_send_voice_notes: true,
    can_send_polls: true,
    can_send_other_messages: true,
    can_add_link_previews: true,
    can_change_info: false,
    can_invite_users: false,
    can_pin_messages: true,
    can_create_topics: false,
  },
  positions: [
    {
      _: 'chatPosition',
      list: { _: 'chatListMain' },
      order: '7611169449991403804',
      is_pinned: false,
    },
  ],
  has_protected_content: false,
  is_translatable: true,
  is_marked_as_unread: false,
  is_blocked: false,
  has_scheduled_messages: false,
  can_be_deleted_only_for_self: true,
  can_be_deleted_for_all_users: true,
  can_be_reported: false,
  default_disable_notification: false,
  unread_count: 0,
  last_read_inbox_message_id: 754063507456,
  last_read_outbox_message_id: 754064556032,
  unread_mention_count: 0,
  unread_reaction_count: 0,
  notification_settings: {
    _: 'chatNotificationSettings',
    use_default_mute_for: true,
    mute_for: 0,
    use_default_sound: true,
    sound_id: '-1',
    use_default_show_preview: true,
    show_preview: false,
    use_default_mute_stories: true,
    mute_stories: false,
    use_default_story_sound: true,
    story_sound_id: '-1',
    use_default_show_story_poster: true,
    show_story_poster: true,
    use_default_disable_pinned_message_notifications: true,
    disable_pinned_message_notifications: false,
    use_default_disable_mention_notifications: true,
    disable_mention_notifications: false,
  },
  available_reactions: {
    _: 'chatAvailableReactionsAll',
    max_reaction_count: 11,
  },
  message_auto_delete_time: 0,
  theme_name: '',
  video_chat: { _: 'videoChat', group_call_id: 0, has_participants: false },
  reply_markup_message_id: 0,
  client_data: '',
} as unknown as Td.chat;

export const CHAT_CHANNEL: Td.chat = {
  _: 'chat',
  id: -1002126425649,
  title: 'Глеб Пройдов',
  type: { _: 'chatTypeSupergroup', supergroup_id: 2126425649, is_channel: true },
  permissions: {
    _: 'chatPermissions',
    can_send_basic_messages: false,
    can_send_audios: false,
    can_send_documents: false,
    can_send_photos: false,
    can_send_videos: false,
    can_send_video_notes: false,
    can_send_voice_notes: false,
    can_send_polls: false,
    can_send_other_messages: false,
    can_add_link_previews: false,
    can_change_info: false,
    can_invite_users: false,
    can_pin_messages: false,
    can_create_topics: false,
  },
  positions: [],
  has_protected_content: false,
  is_translatable: true,
  is_marked_as_unread: false,
  is_blocked: false,
  has_scheduled_messages: false,
  can_be_deleted_only_for_self: false,
  can_be_deleted_for_all_users: false,
  can_be_reported: true,
  default_disable_notification: false,
  unread_count: 0,
  last_read_inbox_message_id: 300941312,
  last_read_outbox_message_id: 2251799812636672,
  unread_mention_count: 0,
  unread_reaction_count: 0,
  notification_settings: {
    _: 'chatNotificationSettings',
    use_default_mute_for: true,
    mute_for: 0,
    use_default_sound: true,
    sound_id: '-1',
    use_default_show_preview: true,
    show_preview: false,
    use_default_mute_stories: true,
    mute_stories: false,
    use_default_story_sound: true,
    story_sound_id: '-1',
    use_default_show_story_poster: true,
    show_story_poster: true,
    use_default_disable_pinned_message_notifications: true,
    disable_pinned_message_notifications: false,
    use_default_disable_mention_notifications: true,
    disable_mention_notifications: false,
  },
  available_reactions: {
    _: 'chatAvailableReactionsSome',
    reactions: [{ _: 'reactionTypeCustomEmoji', custom_emoji_id: '5274008024585871702' }],
    max_reaction_count: 1,
  },
  message_auto_delete_time: 0,
  theme_name: '',
  video_chat: { _: 'videoChat', group_call_id: 0, has_participants: false },
  reply_markup_message_id: 0,
  client_data: '',
} as unknown as Td.chat;

export const FIXTURE_CHATS: Td.chat[] = [
  CHAT_HY_RID,
  CHAT_MARUSIA,
  CHAT_SUPERGROUP,
  CHAT_VALIDOL,
  CHAT_CHANNEL,
];
